site_name: sus-inspector
site_description: The interactive, terminal-based object inspector for suspicious Python objects.
site_author: bwrob
site_url: https://bwrob.github.io/sus-inspector/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: reference.md
