[project]
    authors         = [{ name = "bwrob", email = "bartosz.marcin.wroblewski@gmail.com" }]
    dependencies    = ["rich>=14.3.3", "textual>=8.2.0"]
    description     = "The interactive, terminal-based object inspector for suspicious Python objects."
    name            = "sus-inspector"
    readme          = "README.md"
    requires-python = ">=3.10"
    version         = "0.1.0"

    [project.scripts]
        sus = "sus_inspector:main"

[build-system]
    build-backend = "uv_build"
    requires      = ["uv_build>=0.11.2,<0.12.0"]

[dependency-groups]
    dev = [
        "basedpyright>=1.38.4",
        "poethepoet>=0.42.1",
        "pre-commit>=4.5.1",
        "ruff>=0.15.8",
        "ty>=0.0.26",
    ]
