line-length    = 88
target-version = "py310"

[lint]
    exclude = ["examples", ".prototypes"]
    ignore  = ["COM", "D203", "D211", "D213", "PLR0912", "CPY001"]
    preview = true
    select  = ["ALL"]

[lint.per-file-ignores]
    "tests/**/*" = ["S101"]

[format]
    docstring-code-format = true
